-- ai-books schema snapshot — DO NOT HAND-EDIT.
--
-- Generated by ai_books.db.schema_snapshot from the settled result of applying
-- every supabase/migrations/*.sql file. It is a drift guard (Issue #53), not an
-- executable script: object order is grouped for readability, and the schema
-- name is normalised out so the snapshot is environment-independent.
--
-- Regenerate intentionally after a deliberate DDL change:
--   ./scripts/test.sh  (or set AI_BOOKS_DB_URL) then
--   uv run python -m ai_books.db.schema_snapshot --update


-- ===== ENUM TYPES =====

CREATE TYPE account_type AS ENUM ('asset', 'liability', 'equity', 'revenue', 'expense');

CREATE TYPE entry_side AS ENUM ('debit', 'credit');

CREATE TYPE entry_status AS ENUM ('draft', 'posted', 'voided');

CREATE TYPE normal_side AS ENUM ('debit', 'credit');

-- ===== TABLES =====

CREATE TABLE accounts (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    code text NOT NULL,
    name text NOT NULL,
    account_type account_type NOT NULL,
    statement_category text,
    normal_balance normal_side NOT NULL,
    parent_id bigint,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    actor text NOT NULL,
    tool_name text,
    action text NOT NULL,
    table_name text,
    record_id text,
    before jsonb,
    after jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE fiscal_years (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE journal_entries (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    entry_date date NOT NULL,
    recorded_date date NOT NULL DEFAULT CURRENT_DATE,
    description text,
    voucher_no text,
    source text NOT NULL DEFAULT 'manual'::text,
    status entry_status NOT NULL DEFAULT 'draft'::entry_status,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    void_reason text,
    voided_at timestamp with time zone,
    import_hash text
);

CREATE TABLE journal_lines (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    entry_id bigint NOT NULL,
    line_no integer NOT NULL DEFAULT 1,
    account_id bigint NOT NULL,
    side entry_side NOT NULL,
    amount numeric(18,2) NOT NULL,
    tax_category text,
    sub_account text,
    line_description text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE periods (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    fiscal_year_id bigint NOT NULL,
    name text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE schema_migrations (
    version text NOT NULL,
    applied_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ===== CONSTRAINTS =====

ALTER TABLE accounts ADD CONSTRAINT accounts_code_key UNIQUE (code);

ALTER TABLE accounts ADD CONSTRAINT accounts_no_self_parent CHECK (((parent_id IS NULL) OR (parent_id <> id)));

ALTER TABLE accounts ADD CONSTRAINT accounts_normal_balance_matches_type CHECK ((((account_type = ANY (ARRAY['asset'::account_type, 'expense'::account_type])) AND (normal_balance = 'debit'::normal_side)) OR ((account_type = ANY (ARRAY['liability'::account_type, 'equity'::account_type, 'revenue'::account_type])) AND (normal_balance = 'credit'::normal_side))));

ALTER TABLE accounts ADD CONSTRAINT accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES accounts(id);

ALTER TABLE accounts ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);

ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE fiscal_years ADD CONSTRAINT fiscal_years_date_order CHECK ((end_date > start_date));

ALTER TABLE fiscal_years ADD CONSTRAINT fiscal_years_name_key UNIQUE (name);

ALTER TABLE fiscal_years ADD CONSTRAINT fiscal_years_pkey PRIMARY KEY (id);

ALTER TABLE fiscal_years ADD CONSTRAINT fiscal_years_start_unique UNIQUE (start_date);

ALTER TABLE journal_entries ADD CONSTRAINT journal_entries_pkey PRIMARY KEY (id);

ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id);

ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_amount_positive CHECK ((amount > (0)::numeric));

ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE;

ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_entry_line_unique UNIQUE (entry_id, line_no);

ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_pkey PRIMARY KEY (id);

ALTER TABLE periods ADD CONSTRAINT periods_date_order CHECK ((end_date >= start_date));

ALTER TABLE periods ADD CONSTRAINT periods_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_years(id) ON DELETE CASCADE;

ALTER TABLE periods ADD CONSTRAINT periods_fy_name_unique UNIQUE (fiscal_year_id, name);

ALTER TABLE periods ADD CONSTRAINT periods_pkey PRIMARY KEY (id);

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);

-- ===== INDEXES =====

CREATE INDEX accounts_parent_id_idx ON accounts USING btree (parent_id);

CREATE INDEX audit_logs_created_at_idx ON audit_logs USING btree (created_at);

CREATE INDEX audit_logs_table_record_idx ON audit_logs USING btree (table_name, record_id);

CREATE INDEX journal_entries_entry_date_idx ON journal_entries USING btree (entry_date);

CREATE INDEX journal_lines_account_entry_idx ON journal_lines USING btree (account_id, entry_id);

CREATE INDEX journal_lines_account_id_idx ON journal_lines USING btree (account_id);

CREATE INDEX journal_lines_entry_id_idx ON journal_lines USING btree (entry_id);

CREATE INDEX periods_fiscal_year_id_idx ON periods USING btree (fiscal_year_id);

CREATE UNIQUE INDEX journal_entries_import_hash_key ON journal_entries USING btree (import_hash) WHERE (import_hash IS NOT NULL);

CREATE UNIQUE INDEX journal_entries_voucher_no_key ON journal_entries USING btree (voucher_no) WHERE (voucher_no IS NOT NULL);

-- ===== SEQUENCES =====

CREATE SEQUENCE journal_voucher_no_seq AS bigint START WITH 1 INCREMENT BY 1;

-- ===== FUNCTIONS =====

CREATE OR REPLACE FUNCTION audit_logs_forbid_mutation()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only: % is not permitted', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$function$
;

-- ===== TRIGGERS =====

CREATE TRIGGER audit_logs_no_delete BEFORE DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION audit_logs_forbid_mutation();

CREATE TRIGGER audit_logs_no_truncate BEFORE TRUNCATE ON audit_logs FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_forbid_mutation();

CREATE TRIGGER audit_logs_no_update BEFORE UPDATE ON audit_logs FOR EACH ROW EXECUTE FUNCTION audit_logs_forbid_mutation();
