"""Schema snapshot / migration drift guard (Issue #53).

Renders the *result* of applying every ``supabase/migrations/*.sql`` file — the
settled DDL — as one deterministic, schema-name-independent text artifact. The
artifact is committed as ``tests/fixtures/schema/schema.sql`` (the "golden") and a
DB-backed test re-generates it on a throwaway schema and compares; any drift in
the DDL or the apply order fails the test.

Why introspection, not ``pg_dump``: the project's verification path is
CLI-independent (no ``supabase`` CLI, and ``pg_dump`` is not installed on the
host nor in CI's ``verify`` job). We read the catalog through ``psycopg`` and the
stable ``pg_get_*def`` builtins instead, normalising the throwaway schema name
out so the snapshot is invariant to where it was built (Issue #53 AC: "dump は
環境差(ロール名/順序)に影響されず安定").

Usage::

    uv run python -m ai_books.db.schema_snapshot            # check vs golden (exit 1 on drift)
    uv run python -m ai_books.db.schema_snapshot --update   # rewrite the golden (intentional DDL change)

Raw SQL only — no ORM (AGENTS.md invariant #4).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql

from ai_books.db import get_db_url
from ai_books.db.migrate import apply_pending, default_migrations_dir

#: Committed golden snapshot, compared against the freshly-migrated schema.
GOLDEN_PATH = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "schema" / "schema.sql"

#: Throwaway schema the CLI builds the snapshot in (dropped afterwards).
_BUILD_SCHEMA = "ai_books_schema_snapshot_build"

_HEADER = """\
-- ai-books schema snapshot — DO NOT HAND-EDIT.
--
-- Generated by ai_books.db.schema_snapshot from the settled result of applying
-- every supabase/migrations/*.sql file. It is a drift guard (Issue #53), not an
-- executable script: object order is grouped for readability, and the schema
-- name is normalised out so the snapshot is environment-independent.
--
-- Regenerate intentionally after a deliberate DDL change:
--   ./scripts/test.sh  (or set AI_BOOKS_DB_URL) then
--   uv run python -m ai_books.db.schema_snapshot --update
"""


def _normalize(text: str, schema: str) -> str:
    """Drop the throwaway schema qualifier so the snapshot is schema-independent."""
    return text.replace(f'"{schema}".', "").replace(f"{schema}.", "")


def _enums(conn: psycopg.Connection[Any], schema: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT t.typname, array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
        FROM pg_type t
        JOIN pg_enum e ON e.enumtypid = t.oid
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = %s
        GROUP BY t.typname
        ORDER BY t.typname
        """,
        (schema,),
    ).fetchall()
    out: list[str] = []
    for name, labels in rows:
        rendered = ", ".join(f"'{label}'" for label in labels)
        out.append(f"CREATE TYPE {name} AS ENUM ({rendered});")
    return out


def _table_names(conn: psycopg.Connection[Any], schema: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT c.relname
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relkind = 'r'
        ORDER BY c.relname
        """,
        (schema,),
    ).fetchall()
    return [r[0] for r in rows]


def _columns(conn: psycopg.Connection[Any], schema: str, table: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT a.attname,
               format_type(a.atttypid, a.atttypmod) AS type,
               a.attnotnull,
               a.attidentity,
               pg_get_expr(d.adbin, d.adrelid) AS default_expr
        FROM pg_attribute a
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE a.attrelid = format('%%I.%%I', %s::text, %s::text)::regclass
          AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
        """,
        (schema, table),
    ).fetchall()
    cols: list[str] = []
    for name, col_type, notnull, identity, default_expr in rows:
        parts = [name, col_type]
        if notnull:
            parts.append("NOT NULL")
        if identity == "a":
            parts.append("GENERATED ALWAYS AS IDENTITY")
        elif identity == "d":
            parts.append("GENERATED BY DEFAULT AS IDENTITY")
        elif default_expr is not None:
            parts.append(f"DEFAULT {default_expr}")
        cols.append(" ".join(parts))
    return cols


def _constraints(conn: psycopg.Connection[Any], schema: str, table: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT conname, pg_get_constraintdef(oid) AS def
        FROM pg_constraint
        WHERE conrelid = format('%%I.%%I', %s::text, %s::text)::regclass
        ORDER BY conname
        """,
        (schema, table),
    ).fetchall()
    return [f"ALTER TABLE {table} ADD CONSTRAINT {name} {definition};" for name, definition in rows]


def _indexes(conn: psycopg.Connection[Any], schema: str, table: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT pg_get_indexdef(i.indexrelid) AS def
        FROM pg_index i
        JOIN pg_class c ON c.oid = i.indexrelid
        WHERE i.indrelid = format('%%I.%%I', %s::text, %s::text)::regclass
          AND NOT EXISTS (
              SELECT 1 FROM pg_constraint con WHERE con.conindid = i.indexrelid
          )
        ORDER BY c.relname
        """,
        (schema, table),
    ).fetchall()
    return [f"{definition};" for (definition,) in rows]


def _sequences(conn: psycopg.Connection[Any], schema: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT c.relname,
               format_type(s.seqtypid, NULL) AS data_type,
               s.seqstart,
               s.seqincrement
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_sequence s ON s.seqrelid = c.oid
        WHERE n.nspname = %s
          AND NOT EXISTS (
              SELECT 1 FROM pg_depend d WHERE d.objid = c.oid AND d.deptype = 'i'
          )
        ORDER BY c.relname
        """,
        (schema,),
    ).fetchall()
    return [
        f"CREATE SEQUENCE {name} AS {data_type} START WITH {start} INCREMENT BY {increment};"
        for name, data_type, start, increment in rows
    ]


def _functions(conn: psycopg.Connection[Any], schema: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT pg_get_functiondef(p.oid) AS def
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = %s
        ORDER BY p.proname
        """,
        (schema,),
    ).fetchall()
    return [f"{definition};" for (definition,) in rows]


def _triggers(conn: psycopg.Connection[Any], schema: str) -> list[str]:
    rows = conn.execute(
        """
        SELECT pg_get_triggerdef(t.oid) AS def
        FROM pg_trigger t
        JOIN pg_class c ON c.oid = t.tgrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND NOT t.tgisinternal
        ORDER BY c.relname, t.tgname
        """,
        (schema,),
    ).fetchall()
    return [f"{definition};" for (definition,) in rows]


def dump_schema(conn: psycopg.Connection[Any], schema: str) -> str:
    """Render the DDL of ``schema`` as a deterministic, schema-name-independent text."""
    sections: list[tuple[str, list[str]]] = []

    sections.append(("ENUM TYPES", _enums(conn, schema)))

    table_blocks: list[str] = []
    constraint_lines: list[str] = []
    index_lines: list[str] = []
    for table in _table_names(conn, schema):
        cols = _columns(conn, schema, table)
        body = ",\n".join(f"    {c}" for c in cols)
        table_blocks.append(f"CREATE TABLE {table} (\n{body}\n);")
        constraint_lines.extend(_constraints(conn, schema, table))
        index_lines.extend(_indexes(conn, schema, table))

    sections.append(("TABLES", table_blocks))
    sections.append(("CONSTRAINTS", sorted(constraint_lines)))
    sections.append(("INDEXES", sorted(index_lines)))
    sections.append(("SEQUENCES", _sequences(conn, schema)))
    sections.append(("FUNCTIONS", _functions(conn, schema)))
    sections.append(("TRIGGERS", _triggers(conn, schema)))

    chunks: list[str] = [_HEADER]
    for title, items in sections:
        chunks.append(f"-- ===== {title} =====")
        chunks.append("\n\n".join(items) if items else "-- (none)")
    rendered = "\n\n".join(chunks).rstrip() + "\n"
    return _normalize(rendered, schema)


def build_snapshot(conn: psycopg.Connection[Any], *, schema: str, migrations_dir: Path) -> str:
    """Apply all migrations into a fresh throwaway ``schema`` and return its dump.

    Drops and recreates ``schema`` so the build is repeatable, then drops it again
    on the way out — nothing is left behind in ``public``.
    """
    drop = sql.SQL("DROP SCHEMA IF EXISTS {} CASCADE").format(sql.Identifier(schema))
    try:
        conn.execute(drop)
        conn.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        conn.execute(sql.SQL("SET search_path TO {}").format(sql.Identifier(schema)))
        apply_pending(conn, migrations_dir)
        return dump_schema(conn, schema)
    finally:
        conn.execute(drop)


def read_golden() -> str:
    """Return the committed golden snapshot ('' if it does not exist yet)."""
    return GOLDEN_PATH.read_text(encoding="utf-8") if GOLDEN_PATH.exists() else ""


def write_golden(snapshot: str) -> None:
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(snapshot, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ai_books.db.schema_snapshot",
        description="Generate / check the committed schema drift-guard snapshot.",
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the golden snapshot (use only for an intentional DDL change)",
    )
    parser.add_argument(
        "--database-url",
        default=None,
        help=f"Postgres connection string (default: ${'AI_BOOKS_DB_URL'})",
    )
    args = parser.parse_args(argv)

    try:
        url = args.database_url or get_db_url()
    except RuntimeError as exc:  # AI_BOOKS_DB_URL unset
        print(f"error: {exc}", file=sys.stderr)
        return 2

    with psycopg.connect(url, autocommit=True) as conn:
        snapshot = build_snapshot(
            conn, schema=_BUILD_SCHEMA, migrations_dir=default_migrations_dir()
        )

    if args.update:
        write_golden(snapshot)
        print(f"updated golden snapshot: {GOLDEN_PATH}")
        return 0

    if snapshot == read_golden():
        print("schema snapshot matches the committed golden")
        return 0

    print(
        "schema drift detected: the migrated schema no longer matches "
        f"{GOLDEN_PATH}.\nIf this DDL change is intentional, regenerate with:\n"
        "  uv run python -m ai_books.db.schema_snapshot --update",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
